name: YouTube Live Stream
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5,6,0'
jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 620
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download Video
        run: wget -O video.mp4 "https://www.dropbox.com/scl/fi/558yghq6f3e430qhs9oer/2026-06-14-07.03.26.mp4?rlkey=jqnz7icscji3qb57co2hfl5pj&st=p668xrxe&dl=1"

      - name: Start Stream
        working-directory: ${{ github.workspace }}
        run: |
          chmod +x stream.sh
          bash stream.sh
        env:
          STREAM_KEY: ${{ secrets.STREAM_KEY }}
